"""initial_tables

Revision ID: defe32bf62d1
Revises: 
Create Date: 2026-08-12 10:50:23.791509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'defe32bf62d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('shortfall_date', sa.Date(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='alert'
    )
    op.create_index(op.f('ix_alert_alerts_user_id'), 'alerts', ['user_id'], unique=False, schema='alert')
    op.create_index('ix_alerts_user_shortfall_date', 'alerts', ['user_id', 'shortfall_date'], unique=False, schema='alert')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('alert_threshold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.create_table('bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plaid_item_id', sa.String(length=255), nullable=False),
    sa.Column('encrypted_access_token', sa.LargeBinary(), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bank'
    )
    op.create_index(op.f('ix_bank_bank_accounts_user_id'), 'bank_accounts', ['user_id'], unique=False, schema='bank')
    op.create_table('forecast_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('projected_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'forecast_date', 'generated_date', name='uq_forecast_user_date_generated'),
    schema='forecast'
    )
    op.create_index(op.f('ix_forecast_forecast_snapshots_user_id'), 'forecast_snapshots', ['user_id'], unique=False, schema='forecast')
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id', sa.UUID(), nullable=False),
    sa.Column('plaid_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_transaction_id'),
    schema='txn'
    )
    op.create_index('ix_transactions_account_date', 'transactions', ['bank_account_id', 'date'], unique=False, schema='txn')
    op.create_index(op.f('ix_txn_transactions_bank_account_id'), 'transactions', ['bank_account_id'], unique=False, schema='txn')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False, schema='auth')
    op.create_table('sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('transactions_synced', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank.bank_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='bank'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_logs', schema='bank')
    op.drop_index(op.f('ix_auth_refresh_tokens_user_id'), table_name='refresh_tokens', schema='auth')
    op.drop_index(op.f('ix_auth_refresh_tokens_token_hash'), table_name='refresh_tokens', schema='auth')
    op.drop_table('refresh_tokens', schema='auth')
    op.drop_index(op.f('ix_txn_transactions_bank_account_id'), table_name='transactions', schema='txn')
    op.drop_index('ix_transactions_account_date', table_name='transactions', schema='txn')
    op.drop_table('transactions', schema='txn')
    op.drop_index(op.f('ix_forecast_forecast_snapshots_user_id'), table_name='forecast_snapshots', schema='forecast')
    op.drop_table('forecast_snapshots', schema='forecast')
    op.drop_index(op.f('ix_bank_bank_accounts_user_id'), table_name='bank_accounts', schema='bank')
    op.drop_table('bank_accounts', schema='bank')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_index('ix_alerts_user_shortfall_date', table_name='alerts', schema='alert')
    op.drop_index(op.f('ix_alert_alerts_user_id'), table_name='alerts', schema='alert')
    op.drop_table('alerts', schema='alert')
    # ### end Alembic commands ###
