"""
Alert service — business logic for shortfall notifications.

Controller → Service → Repository → Database
              ^^^^^^
              You are here.

Handles alert formatting, delivery via SendGrid, and alert history retrieval.
Falls back to log-only mode when SENDGRID_API_KEY is not configured.
"""

import uuid
from datetime import date

from sqlalchemy.orm import Session

from app.config import settings
from app.core.constants import AlertType
from app.core.logging_config import get_logger
from app.modules.alert.repositories import alert_repository
from app.modules.alert.schemas.alert_schemas import (
    AlertListResponse,
    AlertResponse,
)

logger = get_logger(__name__)


def _build_alert_html(
    business_name: str,
    shortfall_date: date,
    projected_balance: float,
) -> str:
    """
    Build a professional HTML email body for a shortfall alert.

    Args:
        business_name: The user's business name (for personalization).
        shortfall_date: The projected shortfall date.
        projected_balance: The projected balance on that date.

    Returns:
        HTML string ready for SendGrid.
    """
    formatted_date = shortfall_date.strftime("%B %d, %Y")
    formatted_balance = f"${projected_balance:,.2f}"
    display_name = business_name or "your business"

    return f"""
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px;">
        <div style="background: linear-gradient(135deg, #FF6B6B, #EE5A24); border-radius: 12px; padding: 32px; color: white; text-align: center;">
            <h1 style="margin: 0 0 8px 0; font-size: 24px;">⚠️ Cashflow Alert</h1>
            <p style="margin: 0; opacity: 0.9; font-size: 14px;">CashFlow Forecaster</p>
        </div>

        <div style="padding: 32px 0;">
            <p style="font-size: 16px; color: #333; line-height: 1.6;">
                Hi there,
            </p>
            <p style="font-size: 16px; color: #333; line-height: 1.6;">
                Our forecast for <strong>{display_name}</strong> projects a
                <strong>cashflow shortfall</strong> on
                <strong>{formatted_date}</strong>.
            </p>

            <div style="background: #FFF3F3; border-left: 4px solid #FF6B6B; border-radius: 8px; padding: 20px; margin: 24px 0;">
                <p style="margin: 0 0 8px 0; font-size: 14px; color: #666;">Projected Balance</p>
                <p style="margin: 0; font-size: 28px; font-weight: 700; color: #D63031;">
                    {formatted_balance}
                </p>
                <p style="margin: 8px 0 0 0; font-size: 14px; color: #666;">
                    on {formatted_date}
                </p>
            </div>

            <p style="font-size: 16px; color: #333; line-height: 1.6;">
                <strong>What you can do:</strong>
            </p>
            <ul style="font-size: 15px; color: #555; line-height: 1.8;">
                <li>Review and postpone non-essential upcoming expenses</li>
                <li>Follow up on outstanding invoices or receivables</li>
                <li>Arrange a short-term credit line if needed</li>
            </ul>

            <p style="font-size: 14px; color: #999; margin-top: 32px; border-top: 1px solid #eee; padding-top: 16px;">
                This alert was generated by CashFlow Forecaster based on your
                recent transaction patterns. Log in to your dashboard to see
                the full forecast and adjust your projections.
            </p>
        </div>
    </div>
    """


def _send_email(to_email: str, subject: str, html_content: str) -> bool:
    """
    Send an email via Gmail SMTP.

    Uses Python's built-in smtplib — no external dependency needed.
    Returns True if sent successfully, False on failure.
    Falls back to log-only mode if SMTP credentials are not configured.
    """
    if not settings.SMTP_EMAIL or not settings.SMTP_PASSWORD:
        logger.info(
            f"[LOG-ONLY] SMTP not configured — would send to {to_email}: {subject}"
        )
        return True  # Treat as "sent" in dev mode

    try:
        import smtplib
        from email.mime.multipart import MIMEMultipart
        from email.mime.text import MIMEText

        msg = MIMEMultipart("alternative")
        msg["From"] = f"CashFlow Forecaster <{settings.SMTP_EMAIL}>"
        msg["To"] = to_email
        msg["Subject"] = subject

        # Attach HTML body
        msg.attach(MIMEText(html_content, "html"))

        with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
            server.starttls()
            server.login(settings.SMTP_EMAIL, settings.SMTP_PASSWORD)
            server.send_message(msg)

        logger.info(f"Alert email sent to {to_email} via SMTP")
        return True

    except Exception as e:
        logger.error(f"Failed to send alert email to {to_email}: {e}")
        return False


def send_shortfall_alert(
    db: Session,
    user_id: uuid.UUID,
    user_email: str,
    shortfall_date: date,
    projected_balance: float,
    business_name: str | None = None,
) -> bool:
    """
    Send a shortfall alert notification to a user.

    Flow:
        1. Check idempotency — skip if already alerted for this date
        2. Format the message
        3. Send notification via SendGrid (or log-only in dev)
        4. Record the alert in DB

    Args:
        db: Database session.
        user_id: The user to alert.
        user_email: The user's email for notification delivery.
        shortfall_date: The projected shortfall date.
        projected_balance: The projected balance on that date.
        business_name: Optional business name for personalization.

    Returns:
        True if alert was sent, False if skipped (already alerted).
    """
    # 1. Idempotency check
    if alert_repository.has_alert_for_date(db, user_id, shortfall_date):
        logger.info(
            f"Alert already exists for user {user_id} on {shortfall_date} — skipping"
        )
        return False

    # 2. Format message (plain text for DB record)
    message = (
        f"⚠️ Projected cashflow shortfall on {shortfall_date.strftime('%B %d, %Y')}. "
        f"Your projected balance will be ${projected_balance:,.2f}. "
        f"Consider adjusting upcoming expenses or securing additional funds."
    )

    # 3. Send notification via SendGrid
    subject = (
        f"⚠️ Cashflow Alert: Projected shortfall on "
        f"{shortfall_date.strftime('%b %d, %Y')}"
    )
    html_body = _build_alert_html(
        business_name=business_name or "Your Business",
        shortfall_date=shortfall_date,
        projected_balance=projected_balance,
    )
    sent = _send_email(user_email, subject, html_body)

    # 4. Record in DB (even if email failed — so we don't spam retries)
    alert_repository.create_alert(
        db=db,
        user_id=user_id,
        alert_type=AlertType.PROJECTED_SHORTFALL.value,
        shortfall_date=shortfall_date,
        message=message,
        sent=sent,
    )

    logger.info(
        f"Shortfall alert created for user {user_id}: "
        f"{shortfall_date} (${projected_balance:,.2f}) — "
        f"email {'sent' if sent else 'FAILED'}"
    )

    return True


def get_alert_history(
    db: Session,
    user_id: str,
    skip: int = 0,
    limit: int = 50,
) -> AlertListResponse:
    """
    Get the alert history for a user.

    Returns:
        AlertListResponse with paginated alerts.
    """
    alerts, total = alert_repository.get_alerts_by_user(
        db=db,
        user_id=uuid.UUID(user_id),
        skip=skip,
        limit=limit,
    )

    return AlertListResponse(
        alerts=[
            AlertResponse(
                id=str(a.id),
                alert_type=a.alert_type,
                shortfall_date=a.shortfall_date,
                message=a.message,
                sent=a.sent,
                created_at=a.created_at,
            )
            for a in alerts
        ],
        total=total,
    )
